title: Pendata
author: yogaandrian13
logo: logo.jpg

repository:
  url: https://github.com/yogaandrian13/Pendata
  branch: main

execute:
  execute_notebooks: off

html:
  use_edit_page_button: true
  use_repository_button: true
