# Book settings
title: Pendata
author: yogaandrian13
logo: logo.jpg

# Repository settings
repository:
  url: https://github.com/yogaandrian13/Pendata
  branch: main

# Execution settings
execute:
  execute_notebooks: off

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# HTML settings
html:
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  home_page_in_navbar: true
  extra_footer: ""
  baseurl: https://yogaandrian13.github.io/Pendata/

# Sphinx settings
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_copy_source: true
    html_sourcelink_suffix: ""
    exclude_patterns:
      - ".ipynb_checkpoints"
      - "*~"
    html_static_path:
      - _static
    html_css_files:
      - custom.css
