# Book settings
title: Pendata
author: yogaandrian13
logo: ""

# Execution settings
execute:
  execute_notebooks: off

# HTML settings
html:
  use_edit_page_button: true
  use_repository_button: true
